---
# tasks file for wordpress
- name: git clone
  git:
    repo: https://github.com/michaelbertoni/wordpress-docker-compose.git
    dest: /tmp/wordpress/
    version: master

- name: check if /tmp/wordpress/docker-compose.yml is present
  stat:
    path: /tmp/wordpress/docker-compose.yml
  register: docker_compose_file

- name: fail if there is no docker-compose.yml
  fail:
    msg: "Pas de docker-compose.yml, pas de wordpress mon gars"
  when: docker_compose_file.stat.exists == False

- name: Create db_data volume
  docker_volume:
    name: wordpress_db_data
    state: present

- name: docker-compose pull && docker-compose up -d
  docker_service:
    project_src: /tmp/wordpress/
    pull: true
    state: present

- name: healthcheck wordpress
  uri:
    url: http://localhost:8000
    status_code: 200
  register: result
  until: result.status == 200
  retries: 60
  delay: 1
  delegate_to: localhost

- name: wordpress configuré
  uri:
    url: http://localhost:8000/wp-admin/install.php?step=2
    method: POST
    body: "weblog_title=test&user_name=test&admin_email=test@test.fr&admin_password=test&admin_password2=test&pw_weak=1"
  register: result
  until: result.status == 200
  retries: 60
  delay: 1
  delegate_to: localhost
