---
# tasks file for apache
- name: Inclure les variables spécifiques à la famille d'OS
  include_vars: "{{ ansible_os_family }}.yml"

- name: Installation d'Apache et de PHP (Debian/Ubuntu)
  include_tasks: setup-debian.yml
  when: ansible_os_family == 'Debian'

- name: Installation d'Apache et de PHP (Centos/RedHat)
  include_tasks: setup-redhat.yml
  when: ansible_os_family == 'RedHat'

- name: Activation des modules Apache nécessaires
  apache2_module:
    name: "{{ item }}"
    state: present
  with_items: "{{ apache2_modules }}"

- name: Activation du service au démarrage et lancement
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: true
