---
# tasks file for demo1
- name: Le paquet apache est installé
  package:
    name: "{{ package_name }}"
    state: present
  notify:
    - restart apache

- name: Le service apache est lancé et activé au démarrage
  service:
    name: "{{ service_name }}"
    state: started
    enabled: true
