---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: instance
    image: docker:dind
    privileged: yes
    volumes:
      - /var/lib/docker
    published_ports:
      - 0.0.0.0:12375:2375
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: better
verifier:
  name: testinfra
  lint:
    name: flake8
